# Generated by Django 5.1.6 on 2025-10-17 12:38

import django.db.models.deletion
import halal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistem',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('logis_as', models.CharField(max_length=100)),
                ('jenis_aktivitas', models.CharField(max_length=100)),
                ('waktu_akses', models.DateTimeField(auto_now_add=True)),
                ('status_respon', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LPHAdmin',
            fields=[
                ('id_lph_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('kantor', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRProduk',
            fields=[
                ('id_qr', models.CharField(default=halal.models.generate_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('public_url', models.URLField()),
                ('tanggal_generate', models.DateTimeField(auto_now_add=True)),
                ('status_qr', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='LPHAuditor',
            fields=[
                ('id_lph_auditor', models.AutoField(primary_key=True, serialize=False)),
                ('nama_auditor', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_telepon', models.PositiveBigIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('id_lph_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal.lphadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Manufaktur',
            fields=[
                ('id_manufaktur', models.AutoField(primary_key=True, serialize=False)),
                ('nama_usaha', models.CharField(max_length=300)),
                ('alamat', models.TextField()),
                ('jenis_produk', models.CharField(max_length=100)),
                ('status_halal', models.BooleanField(default=False)),
                ('contact', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('status_akun', models.BooleanField(default=False)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('catatan_regis', models.TextField(blank=True, null=True)),
                ('id_lph_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='halal.lphadmin')),
                ('id_lph_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='halal.lphauditor')),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=100)),
                ('komposisi', models.CharField(max_length=100)),
                ('status_analisis', models.CharField(max_length=100)),
                ('id_manufaktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal.manufaktur')),
                ('id_qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal.qrproduk')),
            ],
        ),
        migrations.CreateModel(
            name='KeputusanSistem',
            fields=[
                ('id_keputusan', models.AutoField(primary_key=True, serialize=False)),
                ('nilai_m', models.BooleanField(default=False)),
                ('nilai_s', models.BooleanField(default=False)),
                ('kombinasi_parameter', models.TextField()),
                ('keputusan_sistem', models.TextField()),
                ('deskripsi_keputusan_sistem', models.TextField()),
                ('rekomendasi_perbaikan', models.TextField()),
                ('tanggal_analisis', models.DateTimeField(auto_now_add=True)),
                ('id_lph_auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal.lphauditor')),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal.produk')),
            ],
        ),
        migrations.CreateModel(
            name='ProdukSupplier',
            fields=[
                ('id_produk_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(max_length=100)),
                ('jenis_bahanbaku', models.CharField(max_length=100)),
                ('asal_bahan', models.CharField(max_length=100)),
                ('status_halal', models.BooleanField(default=False)),
                ('id_lph_auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal.lphauditor')),
            ],
        ),
        migrations.CreateModel(
            name='DetailProdukSupplier',
            fields=[
                ('id_detail_produk_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('peran_supplier', models.CharField(max_length=100)),
                ('catatan_rantai_pasok', models.TextField()),
                ('id_produk_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal.produksupplier')),
                ('id_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal.supplier')),
            ],
        ),
    ]
