# Generated by Django 5.1.6 on 2025-10-21 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='id_lph_auditor',
        ),
        migrations.AddField(
            model_name='supplier',
            name='id_manufaktur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='halal.manufaktur'),
            preserve_default=False,
        ),
    ]
