# Generated by Django 5.1.6 on 2025-10-23 05:57

import django.utils.timezone
import halal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0002_remove_supplier_id_lph_auditor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='id_qr',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='komposisi',
        ),
        migrations.AddField(
            model_name='produk',
            name='qr_code',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='tanggal_generate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produk',
            name='id_produk',
            field=models.CharField(default=halal.models.generate_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='QRProduk',
        ),
    ]
