# Generated by Django 5.1.6 on 2025-10-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0003_remove_produk_id_qr_remove_produk_komposisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
