# Generated by Django 5.1.6 on 2025-11-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0004_alter_produk_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
