# Generated by Django 5.1.6 on 2025-11-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0005_produk_catatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufaktur',
            name='status_halal',
            field=models.CharField(default='Belum Halal', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status_halal',
            field=models.CharField(default='Non Halal', max_length=100),
        ),
    ]
