# Generated by Django 5.1.6 on 2025-11-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0006_alter_manufaktur_status_halal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status_halal',
            field=models.CharField(default='Belum Halal', max_length=100),
        ),
    ]
