# Generated by Django 5.1.6 on 2025-11-07 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0007_alter_supplier_status_halal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BahanBaku',
            fields=[
                ('id_bahanbaku', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bahanbaku', models.CharField(max_length=100)),
                ('nama_supplier', models.CharField(max_length=100)),
                ('status_halal', models.CharField(default='Belum Halal', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='keputusansistem',
            name='id_lph_auditor',
        ),
        migrations.RemoveField(
            model_name='keputusansistem',
            name='id_produk',
        ),
        migrations.DeleteModel(
            name='LogSistem',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='id_manufaktur',
        ),
        migrations.RemoveField(
            model_name='detailproduksupplier',
            name='id_supplier',
        ),
        migrations.RemoveField(
            model_name='detailproduksupplier',
            name='catatan_rantai_pasok',
        ),
        migrations.RemoveField(
            model_name='detailproduksupplier',
            name='peran_supplier',
        ),
        migrations.RemoveField(
            model_name='manufaktur',
            name='status_halal',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='status_analisis',
        ),
        migrations.AddField(
            model_name='manufaktur',
            name='ktp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufaktur',
            name='nib',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='status_halal',
            field=models.CharField(default='Belum Halal', max_length=100),
        ),
        migrations.AddField(
            model_name='produksupplier',
            name='catatan_auditor',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produksupplier',
            name='verifikasi_auditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bahanbaku',
            name='id_manufaktur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal.manufaktur'),
        ),
        migrations.AddField(
            model_name='detailproduksupplier',
            name='id_bahanbaku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='halal.bahanbaku'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='KeputusanSistem',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
