# Generated by Django 5.1.6 on 2025-11-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0008_bahanbaku_remove_keputusansistem_id_lph_auditor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufaktur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='manufaktur',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
