# Generated by Django 5.1.6 on 2025-11-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0009_alter_manufaktur_email_alter_manufaktur_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produksupplier',
            name='catatan_auditor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
